server:
  port: 8082

spring:
  datasource:
    username: root
    password: cai123456
    url: jdbc:mysql://52.77.215.91:3306/monitor?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity




#showSql
logging:
  config: classpath:logback-spring.xml


elasticsearch:
  ip: 54.179.56.210:9200